/**
 * Tarot Data – 22 Major Arcana + Suited Arcana Archetypes
 * Public domain Rider-Waite illustrations with French & English interpretations
 */

const MAJOR_ARCANA = [
  {
    name: 'Le Mat',
    slug: 'le-mat',
    nameFr: 'Le Mat (Le Fou)',
    nameEn: 'The Fool',
    arcana: 'Major',
    suit: null,
    number: 0,
    keywords: ['Nouveau départ', 'Innocence', 'Spontanéité', 'Liberté', 'Saut dans l’inconnu'],
    meaningUpright: 'Le Mat symbolise le commencement d\'une quête spirituelle ou personnelle. C\'est l\'invitation à faire confiance à l\'inconnu, à embrasser l\'inattendu avec innocence et audace.',
    meaningReversed: 'À l\'envers, Le Mat signale de l\'insouciance excessive, une prise de risque irréfléchie, ou au contraire une peur paralysante de se lancer.',
    description: 'Un jeune voyageur marche au bord d\'un précipice sous un soleil éclatant, guidé par son enthousiasme pur et accompagné d\'un petit chien blanc symbole de loyauté.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg',
    element: 'Air',
    planet: 'Uranus',
    zodiacSign: null,
    isActive: true,
  },
  {
    name: 'Le Bateleur',
    slug: 'le-bateleur',
    nameFr: 'Le Bateleur (Le Magicien)',
    nameEn: 'The Magician',
    arcana: 'Major',
    suit: null,
    number: 1,
    keywords: ['Manifestation', 'Ressources', 'Volonté', 'Créativité', 'Pouvoir d\'action'],
    meaningUpright: 'Le Magicien possède tous les outils nécessaires sur sa table pour concrétiser ses visions. C\'est le moment idéal pour agir, créer et transformer vos idées en réalité tangible.',
    meaningReversed: 'Tromperie, manipulation, talents gaspillés ou manque de confiance dans ses propres capacités.',
    description: 'Debout devant un autel portant les 4 symboles des arcanes mineurs, il lève une baguette vers le ciel et pointe la terre de l\'autre main : comme en haut, ainsi en bas.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg',
    element: 'Air',
    planet: 'Mercure',
    zodiacSign: 'Gémeaux',
    isActive: true,
  },
  {
    name: 'La Papesse',
    slug: 'la-papesse',
    nameFr: 'La Papesse (La Grande Prêtresse)',
    nameEn: 'The High Priestess',
    arcana: 'Major',
    suit: null,
    number: 2,
    keywords: ['Intuition', 'Mystère', 'Inconscient', 'Sagesse intérieure', 'Patience'],
    meaningUpright: 'Faites confiance à votre intuition profonde. Les réponses que vous cherchez ne se trouvent pas dans le tumulte extérieur mais dans le silence de votre esprit.',
    meaningReversed: 'Intuition ignorée, secrets toxiques, superficialité ou déconnexion de son monde émotionnel.',
    description: 'Assise entre les colonnes de l\'Ombre et de la Lumière (Boaz et Jakin), voilée devant un rideau de grenades, elle tient les rouleaux sacrés de la sagesse universelle.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg',
    element: 'Eau',
    planet: 'Lune',
    zodiacSign: 'Cancer',
    isActive: true,
  },
  {
    name: 'L’Impératrice',
    slug: 'l-imperatrice',
    nameFr: 'L’Impératrice',
    nameEn: 'The Empress',
    arcana: 'Major',
    suit: null,
    number: 3,
    keywords: ['Abondance', 'Fécondité', 'Beauté', 'Sensualité', 'Création bienveillante'],
    meaningUpright: 'Une période de floraison, de prospérité et de réconfort s\'ouvre. Cultivez vos projets avec tendresse et connectez-vous à la nature et aux plaisirs des sens.',
    meaningReversed: 'Blocage créatif, dépendance affective, négligence de soi ou étouffement de son entourage.',
    description: 'Couronnée de douze étoiles au milieu d\'un champ de blé doré et d\'une forêt luxuriante, elle incarne la Terre-Mère et la fertilité absolue.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg',
    element: 'Terre',
    planet: 'Vénus',
    zodiacSign: 'Taureau',
    isActive: true,
  },
  {
    name: 'L’Empereur',
    slug: 'l-empereur',
    nameFr: 'L’Empereur',
    nameEn: 'The Emperor',
    arcana: 'Major',
    suit: null,
    number: 4,
    keywords: ['Structure', 'Autorité', 'Stabilité', 'Discipline', 'Fondation solide'],
    meaningUpright: 'Le moment exige organisation, stratégie et rigueur. Vous avez la capacité d\'établir l\'ordre dans le chaos et de bâtir un empire durable.',
    meaningReversed: 'Tyrannie, rigidité excessive, contrôle abusif ou au contraire incapacité à faire respecter ses limites.',
    description: 'Assis sur un trône de pierre sculpté de têtes de bélier, vêtu de rouge et tenant le globe impérial, il veille sur les terres avec puissance et souveraineté.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg',
    element: 'Feu',
    planet: 'Mars',
    zodiacSign: 'Bélier',
    isActive: true,
  },
  {
    name: 'Le Pape',
    slug: 'le-pape',
    nameFr: 'Le Pape (Le Hiérophante)',
    nameEn: 'The Hierophant',
    arcana: 'Major',
    suit: null,
    number: 5,
    keywords: ['Tradition', 'Enseignement', 'Éthique', 'Spiritualité', 'Mentor'],
    meaningUpright: 'Recherche de sens, guidage spirituel et transmission de connaissances. Vous êtes invité à apprendre des maîtres ou à transmettre des valeurs saines.',
    meaningReversed: 'Dogmatisme aveugle, rébellion stérile, hypocrisie ou remise en question salvatrice d\'un système oppressif.',
    description: 'Deux disciples sont agenouillés devant le grand enseignant tenant la triple croix papale, bénissant de deux doigts levés l\'assemblée.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg',
    element: 'Terre',
    planet: 'Vénus',
    zodiacSign: 'Taureau',
    isActive: true,
  },
  {
    name: 'L’Amoureux',
    slug: 'l-amoureux',
    nameFr: 'L’Amoureux (Les Amants)',
    nameEn: 'The Lovers',
    arcana: 'Major',
    suit: null,
    number: 6,
    keywords: ['Amour', 'Harmonie', 'Choix crucial', 'Alignement des valeurs', 'Union'],
    meaningUpright: 'Connexion d\'âmes, complicité sincère et décisions guidées par le cœur. Cette carte marque un carrefour où vos choix doivent refléter vos valeurs les plus intimes.',
    meaningReversed: 'Déchirement, désaccord relationnel, conflits de valeurs ou mauvais choix imposé par la peur.',
    description: 'Sous les ailes déployées de l\'ange Raphaël, un homme et une femme se tiennent nus devant l\'arbre de vie et l\'arbre de la connaissance.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg',
    element: 'Air',
    planet: 'Mercure',
    zodiacSign: 'Gémeaux',
    isActive: true,
  },
  {
    name: 'Le Chariot',
    slug: 'le-chariot',
    nameFr: 'Le Chariot',
    nameEn: 'The Chariot',
    arcana: 'Major',
    suit: null,
    number: 7,
    keywords: ['Triomphe', 'Détermination', 'Contrôle', 'Progrès rapide', 'Focus'],
    meaningUpright: 'Victoire par la maîtrise de soi. Vous avancez avec assurance en conciliant les forces contradictoires de votre vie. Foncez vers votre but.',
    meaningReversed: 'Perte de contrôle, agressivité gratuite, obstacles imprévus ou dispersion d\'énergie.',
    description: 'Un guerrier couronné conduit un chariot tiré par deux sphinx (l\'un noir, l\'autre blanc) symbolisant la réconciliation des opposés sous la volonté consciente.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg',
    element: 'Eau',
    planet: 'Lune',
    zodiacSign: 'Cancer',
    isActive: true,
  },
  {
    name: 'La Force',
    slug: 'la-force',
    nameFr: 'La Force',
    nameEn: 'Strength',
    arcana: 'Major',
    suit: null,
    number: 8,
    keywords: ['Courage doux', 'Compassion', 'Patience', 'Maîtrise intérieure', 'Résilience'],
    meaningUpright: 'La vraie puissance réside dans la douceur, la persévérance et l\'amour. Vous êtes capable d\'apprivoiser les épreuves sans violence ni animosité.',
    meaningReversed: 'Doute de soi, faiblesse apparente, colère impulsive ou sentiment d\'impuissance face aux difficultés.',
    description: 'Une femme vêtue de blanc et surmontée de la lemniscate d\'infinité referme délicatement la gueule d\'un lion féroce par la seule grâce de sa tendresse.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg',
    element: 'Feu',
    planet: 'Soleil',
    zodiacSign: 'Lion',
    isActive: true,
  },
  {
    name: 'L’Hermite',
    slug: 'l-hermite',
    nameFr: 'L’Hermite',
    nameEn: 'The Hermit',
    arcana: 'Major',
    suit: null,
    number: 9,
    keywords: ['Introspection', 'Solitude fertile', 'Lanterne de vérité', 'Recherche intérieure'],
    meaningUpright: 'Prenez du recul par rapport au bruit du monde. Cette période de réflexion solitaire vous permet d\'éclairer votre propre chemin et de trouver votre boussole.',
    meaningReversed: 'Isolement douloureux, repli sur soi stérile, rejet des autres ou refus d\'écouter sa voix intérieure.',
    description: 'Un sage encapuchonné au sommet d\'une montagne enneigée tient une lanterne contenant l\'étoile à six branches de la sagesse divine.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Tarot_Nine_of_Wands.jpg',
    element: 'Terre',
    planet: 'Mercure',
    zodiacSign: 'Vierge',
    isActive: true,
  },
  {
    name: 'La Roue de Fortune',
    slug: 'la-roue-de-fortune',
    nameFr: 'La Roue de Fortune',
    nameEn: 'Wheel of Fortune',
    arcana: 'Major',
    suit: null,
    number: 10,
    keywords: ['Destin', 'Cycles', 'Opportunité', 'Tournant majeur', 'Synchronicité'],
    meaningUpright: 'Les cycles tournent en votre faveur. Acceptez le mouvement perpétuel de l\'univers : un coup de chance ou un tournant inattendu se prépare.',
    meaningReversed: 'Période de stagnation, résistance au changement inévitable, malchance passagère.',
    description: 'Une grande roue ornée de lettres hébraïques et alchimiques tourne entre quatre créatures ailées représentant les quatre éléments cosmiques.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg',
    element: 'Feu',
    planet: 'Jupiter',
    zodiacSign: 'Sagittaire',
    isActive: true,
  },
  {
    name: 'La Justice',
    slug: 'la-justice',
    nameFr: 'La Justice',
    nameEn: 'Justice',
    arcana: 'Major',
    suit: null,
    number: 11,
    keywords: ['Équité', 'Vérité', 'Clarté d\'esprit', 'Loi de cause à effet', 'Karma'],
    meaningUpright: 'Toute action porte ses conséquences. Vous êtes invité à faire preuve de rigueur morale, de lucidité impartiale et d\'honnêteté envers vous-même.',
    meaningReversed: 'Injustice, malhonnêteté, déni de responsabilité ou jugement trop sévère envers autrui.',
    description: 'Assise entre deux piliers, elle tient une balance d\'or dans sa main gauche et une épée à double tranchant dressée vers le ciel dans sa main droite.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg',
    element: 'Air',
    planet: 'Vénus',
    zodiacSign: 'Balance',
    isActive: true,
  },
  {
    name: 'Le Pendu',
    slug: 'le-pendu',
    nameFr: 'Le Pendu',
    nameEn: 'The Hanged Man',
    arcana: 'Major',
    suit: null,
    number: 12,
    keywords: ['Lâcher-prise', 'Nouvelle perspective', 'Pause féconde', 'Détachement'],
    meaningUpright: 'Suspension volontaire de l\'action. En changeant votre regard et en acceptant de ne pas tout contrôler, vous découvrez des révélations inattendues.',
    meaningReversed: 'Entêtement inutile, sacrifice sans but, impatience ou refus d\'accepter une évidence.',
    description: 'Suspendu par un pied à un arbre vivant en forme de T, son visage est calme et nimbé d\'une auréole lumineuse d\'illumination spirituelle.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg',
    element: 'Eau',
    planet: 'Neptune',
    zodiacSign: 'Poissons',
    isActive: true,
  },
  {
    name: 'L’Arcane Sans Nom',
    slug: 'l-arcane-sans-nom',
    nameFr: 'La Mort (Renaissance)',
    nameEn: 'Death',
    arcana: 'Major',
    suit: null,
    number: 13,
    keywords: ['Transformation', 'Fin de cycle', 'Renaissance', 'Dépouillement', 'Métamorphose'],
    meaningUpright: 'Ce n\'est pas une fin littérale mais une métamorphose profonde. Laissez partir ce qui est révolu pour permettre au renouveau de fleurir.',
    meaningReversed: 'Peur viscérale du changement, stagnation dans une situation toxique, résistance stérile à l\'évolution.',
    description: 'Un chevalier en armure noire porte un étendard frappé d\'une rose blanche mystique, tandis qu\'à l\'horizon le soleil se lève entre deux tours sacrées.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg',
    element: 'Eau',
    planet: 'Pluton',
    zodiacSign: 'Scorpion',
    isActive: true,
  },
  {
    name: 'Tempérance',
    slug: 'temperance',
    nameFr: 'Tempérance',
    nameEn: 'Temperance',
    arcana: 'Major',
    suit: null,
    number: 14,
    keywords: ['Modération', 'Alchimie', 'Patience', 'Guérison', 'Harmonisation'],
    meaningUpright: 'Trouvez le juste milieu et la paix intérieure. En fusionnant les extrêmes avec douceur, vous régénérez vos énergies vitales.',
    meaningReversed: 'Excès, déséquilibre émotionnel, impatience ou disputes nées d\'un manque d\'écoute mutuelle.',
    description: 'Un ange ailé verse un fluide vital d\'une coupe d\'or dans une coupe d\'argent, un pied posé sur la terre ferme et l\'autre dans l\'eau claire.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg',
    element: 'Feu',
    planet: 'Jupiter',
    zodiacSign: 'Sagittaire',
    isActive: true,
  },
  {
    name: 'Le Diable',
    slug: 'le-diable',
    nameFr: 'Le Diable',
    nameEn: 'The Devil',
    arcana: 'Major',
    suit: null,
    number: 15,
    keywords: ['Attachement', 'Pulsions', 'Illusions', 'Ombre', 'Libération des chaînes'],
    meaningUpright: 'Prise de conscience de vos dépendances matérielles ou émotionnelles. Les chaînes qui vous lient sont plus lâches que vous ne le croyez : reprenez votre pouvoir.',
    meaningReversed: 'Libération imminente, rupture salutaire avec une habitude nocive, triomphe de la clarté sur la manipulation.',
    description: 'Une créature cornue trône au-dessus de deux figures humaines enchaînées par le cou mais dont les liens peuvent être retirés à tout instant.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg',
    element: 'Terre',
    planet: 'Saturne',
    zodiacSign: 'Capricorne',
    isActive: true,
  },
  {
    name: 'La Maison Dieu',
    slug: 'la-maison-dieu',
    nameFr: 'La Tour (La Maison Dieu)',
    nameEn: 'The Tower',
    arcana: 'Major',
    suit: null,
    number: 16,
    keywords: ['Éveil brutal', 'Effondrement salvateur', 'Révélation', 'Libération'],
    meaningUpright: 'L\'éclair de la vérité détruit les constructions fausses et les illusions. Bien que bouleversant, cet électrochoc libère les fondations pour une reconstruction authentique.',
    meaningReversed: 'Évitement précaire de la crise, reconstruction retardée ou peur de voir la vérité en face.',
    description: 'La foudre frappe une tour élevée érigée sur un sommet rocheux, arrachant la couronne et projetant des étincelles de renouveau cosmique.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg',
    element: 'Feu',
    planet: 'Mars',
    zodiacSign: 'Bélier',
    isActive: true,
  },
  {
    name: 'L’Étoile',
    slug: 'l-etoile',
    nameFr: 'L’Étoile',
    nameEn: 'The Star',
    arcana: 'Major',
    suit: null,
    number: 17,
    keywords: ['Espoir', 'Inspiration', 'Foi', 'Guérison spirituelle', 'Sérénité'],
    meaningUpright: 'Après la tempête vient la lumière. L\'Étoile vous promet paix, espoir retrouvé et inspiration céleste. Laissez votre cœur s\'apaiser.',
    meaningReversed: 'Découragement temporaire, manque de foi en l\'avenir, cynisme ou sentiment d\'être déconnecté de ses rêves.',
    description: 'Une jeune femme nue verse l\'eau vive d\'une source céleste sous un ciel illuminé d\'une grande étoile brillante entourée de sept étoiles dorées.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg',
    element: 'Air',
    planet: 'Uranus',
    zodiacSign: 'Verseau',
    isActive: true,
  },
  {
    name: 'La Lune',
    slug: 'la-lune',
    nameFr: 'La Lune',
    nameEn: 'The Moon',
    arcana: 'Major',
    suit: null,
    number: 18,
    keywords: ['Inconscient', 'Intuition', 'Rêves', 'Illusions nocturnes', 'Clairvoyance'],
    meaningUpright: 'Les eaux profondes de l\'imaginaire et des songes. Prenez garde aux mirages mais écoutez les murmures symboliques de vos intuitions cachées.',
    meaningReversed: 'Dissipation de la confusion, fin d\'un cauchemar ou peurs irrationnelles surmontées par la lucidité.',
    description: 'La pleine lune rayonne au-dessus d\'un paysage nocturne où un loup et un chien aboient entre deux tours, tandis qu\'une écrevisse émerge des profondeurs aquatiques.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg',
    element: 'Eau',
    planet: 'Neptune',
    zodiacSign: 'Poissons',
    isActive: true,
  },
  {
    name: 'Le Soleil',
    slug: 'le-soleil',
    nameFr: 'Le Soleil',
    nameEn: 'The Sun',
    arcana: 'Major',
    suit: null,
    number: 19,
    keywords: ['Joie éclatante', 'Succès', 'Vitalité', 'Clarté', 'Chaleur humaine'],
    meaningUpright: 'Rayonnement total, plénitude et triomphe. L\'énergie solaire inonde votre existence de joie, d\'enthousiasme et de prospérité partagée.',
    meaningReversed: 'Optimisme excessif, fierté blessée, mais l\'éclaircie demeure toujours assurée sous peu.',
    description: 'Un enfant rayonnant monte un cheval blanc sous un soleil immense et bienveillant, entouré de tournesols éclatants.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg',
    element: 'Feu',
    planet: 'Soleil',
    zodiacSign: 'Lion',
    isActive: true,
  },
  {
    name: 'Le Jugement',
    slug: 'le-jugement',
    nameFr: 'Le Jugement',
    nameEn: 'Judgement',
    arcana: 'Major',
    suit: null,
    number: 20,
    keywords: ['Appel intérieur', 'Renaissance', 'Rédemption', 'Pardon', 'Nouvelle vie'],
    meaningUpright: 'La trompette sonne pour votre éveil. C\'est l\'heure du grand pardon, de l\'affranchissement du passé et de l\'entrée dans une nouvelle dimension de vie.',
    meaningReversed: 'Auto-critique paralysante, refus de tourner la page, hésitation à répondre à sa vocation.',
    description: 'L\'archange Gabriel souffle dans sa trompette céleste et les âmes émergent libérées et reconnaissantes de leurs anciens tombeaux.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg',
    element: 'Feu',
    planet: 'Pluton',
    zodiacSign: 'Scorpion',
    isActive: true,
  },
  {
    name: 'Le Monde',
    slug: 'le-monde',
    nameFr: 'Le Monde',
    nameEn: 'The World',
    arcana: 'Major',
    suit: null,
    number: 21,
    keywords: ['Accomplissement', 'Totalité', 'Succès absolu', 'Voyage', 'Harmonie suprême'],
    meaningUpright: 'Couronnement d\'un long parcours. Vous atteignez l\'harmonie, la plénitude et l\'intégration parfaite de toutes vos expériences. Célébrez cette apothéose.',
    meaningReversed: 'Proche du but mais dernier effort requis, boucle inachevée à clore avec conscience.',
    description: 'Une danseuse triomphante évolue au centre d\'une couronne de lauriers cosmique, entourée des quatre figures chérubiques de la création universelle.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg',
    element: 'Terre',
    planet: 'Saturne',
    zodiacSign: 'Capricorne',
    isActive: true,
  },
];

module.exports = { MAJOR_ARCANA };
